###
GET http://localhost:3000/api/modules
###
GET http://localhost:3000/api/modules?id=673483f343fd72cfce5262fb
###
POST http://localhost:3000/api/modules
Content-Type: application/json

{
    "name":"algo warrior 3",
    "mentor_name":"shadow warrior 3",
    "seasonBy":"673ca0caa30067c65c9c3270"
}

    # name: String,
    # mentor_name: { type: String, required: false, default: null },
    # lessons: [{ type: Schema.Types.ObjectId, ref: "Lesson" }],
    # season: { type: Schema.Types.ObjectId, ref: "Season" },
###
DELETE http://localhost:3000/api/modules?id=6733bf53c80b29efece7bafd