import { Inter } from "next/font/google";
import "./globals.css";
import MySidebar from "@/components/organisms/MySidebar/MySidebar";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "lesson-keeper",
  description: "Generated by Shadow",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="main-container" className="">
          {children}
        </div>
        <MySidebar />
      </body>
    </html>
  );
}
