import "./globals.css";
import { Poppins } from "next/font/google";
import MySidebar from "@/components/organisms/MySidebar/MySidebar";
import { ClerkProvider } from "@clerk/nextjs";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});
export const metadata = {
  title: "lesson-keeper",
  description: "Generated by Shadow",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body className={poppins.className}>
          <div>{children}</div>
          <MySidebar />
        </body>
      </html>
    </ClerkProvider>
  );
}
