###
GET http://localhost:3000/api/seasons
###
GET http://localhost:3000/api/seasons?userId=user_2pAnso6bNFShbNcsTbMjlsmkVnd
###
GET http://localhost:3000/api/seasons?id=673ca0a3a30067c65c9c326d
###
POST http://localhost:3000/api/seasons
Content-Type: application/json

{
    "name":"shadow season 3",
    "userBy":"673b1085a65a0d8f01932814"
}
###
PUT http://localhost:3000/api/seasons

{
    "name":"test 01",
    "modules":[]
}
###
DELETE http://localhost:3000/api/seasons?id=673483b643fd72cfce5262f3
